# This is a basic workflow to help you get started with Actions


# Controls when the action will run. 
on: push
  # Triggers the workflow on push or pull request events but only for the main branch


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: 环境信息
        run: cat /etc/issue; python --version

      - name: Install Requires
        run: pip install pytest pytest-cov Pylint flake8 mypy bandit

      # Runs a single command using the runners shell
      - name: Pylint
        run: pylint ciproj

      # Runs a set of commands using the runners shell
      - name: flake8
        run: flake8 ciproj

      - name: pytest
        run: pytest  --showlocals --color=no --cov-report html --cov-config=.coveragerc --cov ciproj tests
