# This is a basic workflow to help you get started with Actions


# Controls when the action will run. 
on: [push, pull_request]
  # Triggers the workflow on push or pull request events but only for the main branch


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  PrePackaging:
    strategy:
      matrix:
        python: [ 3.6, 3.8, 3.9, pypy3 ]
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
    # The type of runner that the job will run on
    runs-on: ${{matrix.platform}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Requires
        run: pip install pytest pytest-cov Pylint flake8 mypy bandit

      # Runs a single command using the runners shell
#      - name: Pylint
#        run: pylint ciproj

      # Runs a set of commands using the runners shell
      - name: flake8
        run: flake8 ciproj

      - name: pytest
        run: pytest --verbose  --showlocals --color=no --cov-config=.coveragerc --cov ciproj tests
      - name: 安全编码
        run: bandit -r ciproj/
